In [19]:
# enables the efficuent array operations
# data processing is easier with numpy array compared to list

import numpy as np 


# Create a 1D array
arr1 = np.array([1, 2, 3, 4, 5])

# Create a 2D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])

print(arr1)
print(arr2)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


In [20]:
#like the list in Python , numpy arrays are also mutable , which means we can change the values

arr1[0] = 10
print(arr1)


[10  2  3  4  5]


In [21]:
### we can have 1D or 2D or even higher dimensional arryas in numpy , say in real time , we have data processing 
### in layers which can be represented as 3D arrays or even higher dimensional arrays , so numpy is very useful in that case
# way how a 2D array can be accessed is by using the row and column index
print(arr2[0][1]) # accessing the element at row 0 and column 1
print(arr2[1][2]) # accessing the element at row 1 and column 2


2
6


In [22]:
#curious about arrays 3D ?

# Creating a 3D array
# 3D array: shape (2, 3, 4)
# why in numpy the shape is 2,3,4 ? because we have 2 layers (z-axis), each layer has 3 rows (y-axis) and each row has 4 columns (x-axis)
arr3d = np.array([
    [  # z = 0
        [1, 2, 3, 4],    # y = 0
        [5, 6, 7, 8],    # y = 1
        [9, 10, 11, 12]  # y = 2
    ],
    [  # z = 1
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]
    ]
])

print(arr3d)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [23]:
#MSE - real usage of numpy in calculating mean squre error bw predicted and actual values.
import numpy as np

# Actual vs predicted values
actual = np.array([3.0, -0.5, 2.0, 7.0])
predicted = np.array([2.5, 0.0, 2.0, 8.0])

# Calculate MSE
mse = np.mean((actual - predicted) ** 2)
print(f"MSE: {mse}")  # Output: 0.375

MSE: 0.375


In [24]:
#median calculation 
import numpy as np

data = np.array([2, 4, 6, 8, 10])
median = np.median(data)  # 6.0
print(f"Median: {median}")

Median: 6.0


In [25]:
# np.zeros(), np.ones(), np.empty(), np.arange(), np.linspace()
np.zeros((2, 3))  # 2D array of zeros with shape (2, 3)
np.ones((3, 4))   # 2D array of ones with shape (3,4)
np.empty((2, 2))  # 2D array of uninitialized values with

array([[0.25, 0.25],
       [0.  , 1.  ]])

In [26]:
#empty array is null array or array that has uninitialized values 
empty_1d = np.empty([])  # 1D array of uninitialized values with length 5
print(empty_1d) #uninitialized values can be anything, it can be random values or it can be garbage values
print(empty_1d.shape) 


1.0
()


In [27]:
# Customer data analysis
customer_ids = np.array([101, 102, 103, 104, 105])
purchases = np.array([5000, 2000, 8000, 1500, 6000])

# Find high-value customers (purchases > 5000)
high_value_ids = np.empty(0, dtype=int)

for i, purchase in enumerate(purchases):
    if purchase > 5000:
        high_value_ids = np.append(high_value_ids, customer_ids[i])

print(f"High-value customers: {high_value_ids}")  # [101, 103, 105]

High-value customers: [103 105]


In [28]:
np.linspace(0, 10, 5)  # 5 evenly spaced numbers between 0 and 10

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [30]:
import numpy as np
import matplotlib.pyplot as plt

# Create smooth curve for sine function
x = np.linspace(0, 2*np.pi, 100)  # 100 evenly spaced points
y = np.sin(x)

plt.plot(x, y)
plt.show()

# Without linspace (using range) would give jagged curve with few points

ModuleNotFoundError: No module named 'matplotlib'

In [33]:
import numpy as np
import pandas as pd

# Real-world CSV with missing values
data = np.array([10, 20, np.nan, 40, 50])

# Trying to calculate statistics
print(np.mean(data))      # nan (propagates)
print(np.std(data))       # nan
print(np.max(data))       # nan

# This is the MOST common NaN error in data science!

nan
nan
nan


In [34]:
import pandas as pd
import numpy as np

# Create DataFrame from dictionary with missing values (NaN)
# Simulating a real-world scenario: Employee data with missing income information
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Age': [25, np.nan, 35, 40, 28],
    'Income': [50000, 60000, np.nan, 75000, np.nan]
}

df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)
print("\n")

# Identify NaN values
print("Detecting NaN values:")
print(df.isna())  # Shows True where NaN exists
print("\n")

# Count NaN in each column
print("NaN count in each column:")
print(df.isna().sum())
print("\n")

# Find rows with any NaN
print("Rows with any NaN:")
print(df[df.isna().any(axis=1)])
print("\n")

# Statistical operations with NaN
print("Operations affected by NaN:")
print(f"Mean Age (with NaN): {df['Age'].mean()}")  # Returns NaN
print(f"Mean Age (ignoring NaN): {df['Age'].mean()}")  # pandas automatically ignores NaN!
print(f"Mean Income: {df['Income'].mean()}")  # Only 2 values: (50000 + 75000) / 2
print(f"Total Income: {df['Income'].sum()}")  # Ignores NaN automatically
print("\n")

# Accessing NaN values
print("Income values:")
print(df['Income'])
print(f"\nAge values:")
print(df['Age'])

Original DataFrame:
      Name   Age   Income
0    Alice  25.0  50000.0
1      Bob   NaN  60000.0
2  Charlie  35.0      NaN
3    David  40.0  75000.0
4      Eve  28.0      NaN


Detecting NaN values:
    Name    Age  Income
0  False  False   False
1  False   True   False
2  False  False    True
3  False  False   False
4  False  False    True


NaN count in each column:
Name      0
Age       1
Income    2
dtype: int64


Rows with any NaN:
      Name   Age   Income
1      Bob   NaN  60000.0
2  Charlie  35.0      NaN
4      Eve  28.0      NaN


Operations affected by NaN:
Mean Age (with NaN): 32.0
Mean Age (ignoring NaN): 32.0
Mean Income: 61666.666666666664
Total Income: 185000.0


Income values:
0    50000.0
1    60000.0
2        NaN
3    75000.0
4        NaN
Name: Income, dtype: float64

Age values:
0    25.0
1     NaN
2    35.0
3    40.0
4    28.0
Name: Age, dtype: float64


In [36]:
# Different strategies to handle NaN values

# Strategy 1: Remove rows with NaN
print("Strategy 1: Remove rows with NaN")
df_clean = df.dropna()
print(df_clean)
print(f"Original rows: {len(df)}, After dropping NaN: {len(df_clean)}\n")

# Strategy 2: Fill NaN with a specific value
print("Strategy 2: Fill NaN with specific values")
df_filled_zero = df.fillna(0)
print("Filled with 0:")
print(df_filled_zero)
print("\n")

# Strategy 3: Fill NaN with mean value
print("Strategy 3: Fill NaN with mean value")
df_filled_mean = df.copy()
df_filled_mean['Age'] = df_filled_mean['Age'].fillna(df_filled_mean['Age'].mean())
df_filled_mean['Income'] = df_filled_mean['Income'].fillna(df_filled_mean['Income'].mean())
print(df_filled_mean)
print("\n")

# Strategy 4: Forward fill (use previous value)
print("Strategy 4: Forward fill")
df_ffill = df.fillna(method='ffill')
print(df_ffill)
print("\n")

# Strategy 5: Backward fill (use next value)
print("Strategy 5: Backward fill")
df_bfill = df.fillna(method='bfill')
print(df_bfill)
print("\n")

# Strategy 6: Interpolate (estimate missing values)
print("Strategy 6: Interpolate")
df_interp = df.copy()
df_interp['Age'] = df_interp['Age'].interpolate()
df_interp['Income'] = df_interp['Income'].interpolate()
print(df_interp)

Strategy 1: Remove rows with NaN
    Name   Age   Income
0  Alice  25.0  50000.0
3  David  40.0  75000.0
Original rows: 5, After dropping NaN: 2

Strategy 2: Fill NaN with specific values
Filled with 0:
      Name   Age   Income
0    Alice  25.0  50000.0
1      Bob   0.0  60000.0
2  Charlie  35.0      0.0
3    David  40.0  75000.0
4      Eve  28.0      0.0


Strategy 3: Fill NaN with mean value
      Name   Age        Income
0    Alice  25.0  50000.000000
1      Bob  32.0  60000.000000
2  Charlie  35.0  61666.666667
3    David  40.0  75000.000000
4      Eve  28.0  61666.666667


Strategy 4: Forward fill
      Name   Age   Income
0    Alice  25.0  50000.0
1      Bob  25.0  60000.0
2  Charlie  35.0  60000.0
3    David  40.0  75000.0
4      Eve  28.0  75000.0


Strategy 5: Backward fill
      Name   Age   Income
0    Alice  25.0  50000.0
1      Bob  35.0  60000.0
2  Charlie  35.0  75000.0
3    David  40.0  75000.0
4      Eve  28.0      NaN


Strategy 6: Interpolate
      Name   Age   Inco

/var/folders/3t/0qs889856gd7mjkxpzrhvr980000gn/T/ipykernel_2080/1491909485.py:26: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_ffill = df.fillna(method='ffill')
/var/folders/3t/0qs889856gd7mjkxpzrhvr980000gn/T/ipykernel_2080/1491909485.py:32: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_bfill = df.fillna(method='bfill')


In [ ]:
import pandas as pd

from IPython.core.interactiveshell import InteractiveShell

InteractiveShell.ast_node_interactivity = "all"

# Create DataFrames

married = pd.DataFrame({
    "emp_id": (1,2,3,4,5,6,7,8),
    "Married": ['John','James','Harper','Amy','Mia','Liz','Benjamin','Ava']
})

homeowners = pd.DataFrame({

    "emp_id": (9,10,11,12,5,6,7,8),

    "Homeowners": ['Sophia','William','Jacob','Michael','Mia','Liz','Benjamin','Ava']

})

# Understanding `InteractiveShell.ast_node_interactivity = "all"`

## Why Do We Use This?

This line controls **how many outputs** are displayed from a Jupyter cell.

**Default Behavior (without this setting):**
- Only the **LAST** expression output is shown
- Previous expressions are evaluated but their output is hidden

**With `"all"` setting:**
- **EVERY** expression output is displayed
- Useful for exploring and debugging data

---

## Comparison: Before vs After

### Example: Without the Setting (Default)
```python
a = [1, 2, 3]
b = [4, 5, 6]
c = a + b
print(f"Sum: {c}")
a  # Only this shows output
```
**Output:** Only shows `[1, 2, 3]` (the last expression)

### Example: With the Setting
```python
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

a = [1, 2, 3]
b = [4, 5, 6]
c = a + b
print(f"Sum: {c}")
a
b  # Now this also shows!
```
**Output:** Shows all outputs including `[4, 5, 6]`


In [ ]:
# Practical Example: Why This Setting is Useful
import pandas as pd
import numpy as np

print("=" * 70)
print("PRACTICAL EXAMPLE: DataFrame Inspection")
print("=" * 70)

# Create a sample DataFrame
df_example = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Score': [95, 87, 92],
    'Grade': ['A', 'B', 'A']
})

print("\nWithout InteractiveShell.ast_node_interactivity = 'all':")
print("You would only see the LAST output below:\n")
print("❌ df_example.shape")
print("❌ df_example.head()")
print("✅ df_example.dtypes  <- ONLY this shows in default Jupyter\n")

print("=" * 70)
print("With InteractiveShell.ast_node_interactivity = 'all':")
print("You see ALL outputs:\n")
print("✅ df_example.shape")
print("✅ df_example.head()")
print("✅ df_example.dtypes\n")

# Now demonstrate with the setting ALREADY enabled
print("Currently, 'ast_node_interactivity' is set to 'all'")
print("So all of these should show output:\n")

# Shape
df_example.shape

In [ ]:
# All outputs below now display!
df_example.head()
df_example.dtypes
df_example.describe()

## When to Use `ast_node_interactivity = "all"`

| Scenario | Use It? | Why? |
|----------|---------|------|
| **Data Exploration** | ✅ Yes | Quickly inspect multiple outputs |
| **EDA (Exploratory Data Analysis)** | ✅ Yes | View shape, dtypes, head() together |
| **Debugging** | ✅ Yes | See intermediate variable outputs |
| **Learning/Tutorial** | ✅ Yes | Educational to see all results |
| **Production Code** | ❌ No | May produce unnecessary output |
| **Final Presentations** | ❌ No | Better to use `print()` for clarity |

---

## Summary

| Aspect | Details |
|--------|---------|
| **What it does** | Makes Jupyter show output from ALL expressions, not just the last one |
| **Default** | Only shows the last expression's output |
| **Use case** | Perfect for data exploration and debugging |
| **Implementation** | Two lines at the top of your notebook |
| **Performance** | Minimal impact - just controls display, not computation |

**Best Practice:** Use it at the **beginning of your notebook** for exploration. Remove or disable for production notebooks.
