In [1]:
# enables the efficuent array operations
# data processing is easier with numpy array compared to list

import numpy as np 

import numpy as np

# Create a 1D array
arr1 = np.array([1, 2, 3, 4, 5])

# Create a 2D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])

print(arr1)
print(arr2)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


In [3]:
#like the list in Python , numpy arrays are also mutable , which means we can change the values

arr1[0] = 10
print(arr1)


[10  2  3  4  5]


In [ ]:
### we can have 1D or 2D or even higher dimensional arryas in numpy , say in real time , we have data processing 
### in layers which can be represented as 3D arrays or even higher dimensional arrays , so numpy is very useful in that case
# way how a 2D array can be accessed is by using the row and column index
print(arr2[0][1]) # accessing the element at row 0 and column 1
print(arr2[1][2]) # accessing the element at row 1 and column 2


2
6


In [ ]:
#curious about arrays 3D ?

# Creating a 3D array
# 3D array: shape (2, 3, 4)
# why in numpy the shape is 2,3,4 ? because we have 2 layers (z-axis), each layer has 3 rows (y-axis) and each row has 4 columns (x-axis)
arr3d = np.array([
    [  # z = 0
        [1, 2, 3, 4],    # y = 0
        [5, 6, 7, 8],    # y = 1
        [9, 10, 11, 12]  # y = 2
    ],
    [  # z = 1
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]
    ]
])

print(arr3d)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
